name: Build Windows Tool

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile C to Windows Executable
        run: |
          gcc main.c -o send_number.exe -lhid -lsetupapi

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-cli-tool
          path: send_number.exe
